### ISSUE TITLE
SafeMathChainlink not used

### ISSUE THREAD

**Issue by jglo0708** [jglo0708/unicash#7]
The contracts should only call the contracts they use. 
At the moment Neither contract uses SafeMathChainlink and AgregatorV3 is used only in TokenUni

**Comment by domenique9** [comment]
Shouldn't we merge it with Margot's work?

**Comment by jglo0708** [comment]
yes, we should. THe point is the existing contracts have unlinked references

**Comment by LacombeLouis** [comment]
not anymore, i think, shoudl all be good
